### ISSUE TITLE
Third party server support for 7.1.1?

### ISSUE THREAD

**Issue by vamsipavanmahesh** [elastic/elasticsearch-rails#1001]
I understand that ES is not going to support communication with servers maintained by 3rd parties.

Looks like the `elasticsearch-ruby` already added the check here
https://github.com/elastic/elasticsearch-ruby/commit/8a0e6d8f98e1f9670bcc749bc615796fc9b68ddb#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

I assume that the same will happen to this repo.

we are currently using the elastic search cluster of amazon and it will take some time for us to migrate to the official ES cluster.

for the time being, my rails app has this:

```ruby
gem 'elasticsearch-model', '7.1.1'
gem 'elasticsearch-rails', '7.1.1'
```

Please let us know if we are covered for the time being and hopefully, nothing will break?

**Comment by picandocodigo** [comment]
Hi @vamsipavanmahesh,
Since `elasticsearch-model` depends on `elasticsearch ~> 7`, I'd suggest locking this dependency in your app's Gemfile to be less than `7.14`, the version where the check was introduced:
```
gem 'elasticsearch-model', '7.1.1'
gem 'elasticsearch-rails', '7.1.1'
gem 'elasticsearch', '< 7.14'
```
This way you'll get the latest version of `elasticsearch-ruby` before 7.14 if you update your gems.

**Comment by vamsipavanmahesh** [comment]
Thanks @picandocodigo for your inputs :)
