### ISSUE TITLE
Sort option is ignored with kaminari

### ISSUE THREAD

**Issue by DSalko** [elastic/elasticsearch-rails#258]
Hello

I'm trying to use ES sort option like 

```
 @results = self.search( { 
                  :query => {
                        ....
                      } 
                   } ) , 
                  :sort => [
                    { :created_at => :desc }
                  ] } )
```

and paginate results like this with _Kaminari_ gem

```
@results.page( page ).per(50).records
```

And appears that :sort option doesn't affect results at all. I'm also using _Mongoid_. Any suggestions? 

Thanks.

**Comment by JamesHarrison** [comment]
We just hit this issue with Mongoid, Kaminari and es-rails - in (re)tire it appears that the preservation of search result ordering is done on the (equivalent) records call if the records are loaded (see https://github.com/karmi/retire/blob/master/lib/tire/results/collection.rb#L149), but in elasticsearch-rails/model this isn't the case.

**Comment by karmi** [comment]
The `to_a` is important -- when you see the code of the adapters, _that_ is the place where the re-ordering of records (based on order of _results_) is being done.

@JamesHarrison Can you be more specific? I'm getting lost in the discussion :)

**Comment by JamesHarrison** [comment]
Specifically, Kaminari (and I assume other paginators) assume you're passing in the records object, along with associated metadata about number of pages of results, total max results, etc. While you can pass Kaminari a raw array it's not the recommended way to use it. Having to call to_a in order to get the results back sorted means Kaminari doesn't get sorted results, because it doesn't call to_a as it can just enumerate results directly off the returned records.

In Tire, if you called .results you got a sorted set of results without any further calls. Monkeypatching es-rails to do the same doesn't appear to cause any issues, and I'm not sure why the sorting code should be isolated and only called on to_a in es-rails

**Comment by salimane** [comment]
any update on this ?

**Comment by ain** [comment]
Reproduced on PostgreSQL. `to_a` did not resolve.

**Comment by pacuna** [comment]
I had the same issue with MySQL. I was applying a random score function and it was being ignored. I added to_a and then it worked.
