### ISSUE TITLE
Getting URL parameter '....' is not supported for facets or aggs using elasticsearch-persistence

### ISSUE THREAD

**Issue by infiniteiteration** [elastic/elasticsearch-rails#348]
I'm using `elasticsearch-persistence`. I have a search query like that:

    search q, size: per_page, from: page-1,
                  aggs: {
                      timeline: {
                          histogram: {
                              field: 'published_at',
                              time_interval: '1y'
                          }
                      }
                  }

I tried to use `facets` as well but I get `URL parameter 'aggs' is not supported`.  Why is that? Thank you for your help!

**Comment by karmi** [comment]
That's because you're using the "simple query in URL parameter" variant, see example here: http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#search-instance_method

Which is because of: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/searching.rb#L31

When you pass the search definition as a Hash, the aggregations (or facets, but those are going away in future) should be returned as part of the response.

Check out the https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-dsl gem for building search definitions programatically!

**Comment by fifigyuri** [comment]
Thank you @karmi, it helped. I appreciate how the elasticsearch for ruby/rails is designed and also your help.

**Comment by infiniteiteration** [comment]
Thank you @karmi, it helped. I appreciate how the elasticsearch for ruby/rails is designed and also your help.

**Comment by karmi** [comment]
@infiniteiteration Thanks!, closing the issue then.
