### ISSUE TITLE
Model relationships

### ISSUE THREAD

**Issue by gthorsen** [elastic/elasticsearch-rails#349]
Is it possible to define relationships in models using elasticsearch-persistence?  So if I have two models I've stored as indexes in ES, Articles and Comments for example, where an Article has many comments, and a comment belongs to an Article, does it understand these relationships?

**Comment by karmi** [comment]
No, it doesn't provide any `belongs_to` or `has_many` semantics.

These would be expressed as a parent<>child relationship in Elasticsearch in most cases, and while it would be possible to provide some DSL methods for that, in the near future I plan to work on other things...

One reason is that I worry a little to provide "too much" abstraction here, since expressing the relationship is quite easy already. Have a look at the `music` example application, which has a Artist<>Album relationship, using the regular `mapping...indexes` DSL of the model integration: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/examples/music/album.rb#L15

**Comment by karmi** [comment]
@gthorsen Hi, any news here?

**Comment by gthorsen** [comment]
I think the one-to-many relationship is straightforward enough, but the many-to-many remains a challenge.
