### ISSUE TITLE
Customized serialization logic applied to updates?

### ISSUE THREAD

**Issue by loren** [elastic/elasticsearch-rails#375]
The serialize/deserialize methods only seem to get called on MyModel.create, not on my_model.update. Is that the intended behavior?

**Comment by karmi** [comment]
Can you please provide more context so I don't have to guess? So this is about the "persistence model"? Do you have any code to demonstrate the issue? Or pointers to source?

**Comment by loren** [comment]
Sorry, here's a snippet. Let me know if you need more context. I'm not sure it's an issue as much as it is confusion on my part as to what is supposed to happen.

```ruby
class Document
  include Elasticsearch::Persistence::Model

  gateway do
    def serialize(document)
      # my custom logic
    end

    def deserialize(hash)
      # my custom logic
    end
  end
end

Document.create(my_attributes_hash) # this uses the serialize method above
document = Document.find(id) # this uses the deserialize method above
document.update(foo: 123) # this does not use the serialize method above
```

**Comment by karmi** [comment]
@loren Sorry for missing this for two weeks, please ping me again if I lose track! This looks like a bug or inconsistency, based on the source, we don't call the `serialize` method at all in the `update` method as opposed to the `save` method (https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-persistence/lib/elasticsearch/persistence/repository/store.rb#L38-L69).

I think though there's a reason for that, since in the `update` method, you usually provide just a list of separate attributes to update, and you probably already somehow transform/manipulate them... Do you have a use case so I can broaden my perspective/thinking about this?

**Comment by loren** [comment]
No problem for the delay. The stuff I am doing with it is open source, albeit work-in-progress, so I can just point you at the code and you can see the use case for yourself.

Look at the [create](https://github.com/GSA/i14y/blob/master/app/controllers/api/v1/documents.rb#L80) vs [update](https://github.com/GSA/i14y/blob/master/app/controllers/api/v1/documents.rb#L127) blocks in this API controller:
https://github.com/GSA/i14y/blob/master/app/controllers/api/v1/documents.rb

When creating a [Document](https://github.com/GSA/i14y/blob/master/app/models/document.rb), I just call `Document.create` and rely on Elasticsearch Persistence to call the `serialize` method.

But when updating a Document, I have to do it manually.

**Comment by karmi** [comment]
Thanks, I can see what you're doing in [`serde.rb`](https://github.com/GSA/i14y/blob/master/lib/serde.rb).

The mental trouble I still have is that a `Hash` of attributes is passed to the `update` method, as opposed to a full object in case of eg. `save`. So when you define a `serialize` method which expects the object (which I imagine is the default), it won't work with the `Hash`, or you would need to implement it so it can work with both... Let me think about it some more and ask around...
