### ISSUE TITLE
providing search_type

### ISSUE THREAD

**Issue by o-r-r** [elastic/elasticsearch-rails#415]
Hi,
From the docs for [elasticsearch-model searching] (http://www.rubydoc.info/gems/elasticsearch-model/#Searching) it's hard to understand how to supply options like search_count. for example if I try the following call:
```ruby
res = MyModel.search  search_type: 'count' , query:     query, aggs: aggs
```
where query, and aggs are valid query and aggs object, when trying to access res.response I receive the following error:

>nested: SearchParseException[[articles_events][4]: from[-1],size[-1]: Parse Failure [No parser for element [search_type]]]; }]","status":400}

removing search_type: 'count'  removes the error as well.

Is there an example of providing the options arg?

Thanks

**Comment by triplepointfive** [comment]
Hi @o-r-r 
In your case search_type is considered as a body key, like `{ search_type: ..., query: ..., ..}`, but is supposed to be an option for search. This is happening because it's considered as a single hash, so your line is equal to:

```ruby
MyModel.search { search_type: 'count' , query:     query, aggs: aggs }
```

But options is a second argument, so it should be like

```ruby
MyModel.search  { query:     query, aggs: aggs }, search_type: 'count'
```

instead.

**Comment by o-r-r** [comment]
Thanks.
Got it to work eventually by something similar:
```MyModel.search  { query:     query, aggs: aggs },  { :timeout => 3 , :search_type => 'count'}```
