### ISSUE TITLE
ActiveRecord callbacks firing on after_commit can lead to inconsistent document state

### ISSUE THREAD

**Issue by cgagon** [elastic/elasticsearch-rails#475]
There's a problem with the indexing strategy here when updating documents:

https://github.com/elastic/elasticsearch-rails/blob/738c63efacc167b6e8faae3b01a1a0135cfc8bbb/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb#L70

The way this is currently written, when updating an existing AR record, the changes are applied and the database transaction is committed, then the rails app will call the index api in ES to index the changed document.  Any number of conditions can occur during this remote call that can result in divergence of the database record from the ES document, including the most likely fault causes: 

a) http transport error 
b) index mapping inconsistency error (bad data in the request)
c) version conflict from ES optimistic concurrency control for the given document when concurrent writes from threads or multiple processes are working against the same document (I've observed this in production and have had to devise workarounds by rewriting these callbacks)

Since there is no way to obtain a transaction or resource lock equivalent from the ES server (by design), isn't it risky to commit the database transaction prior to verifying that that ES cluster has received the same data?

Perhaps we could provide an alternative callback strategy (after_update) that can be configured when including the Callbacks mixin that will run callbacks prior to the commit.  That way if there is any issue, the database transaction is rolled back and you are left in a consistent state with respect to the ES document.

**Comment by karmi** [comment]
Hi, so I think this is something like a "chicken and egg" problem.

In ActiveRecord [callbacks](http://api.rubyonrails.org/classes/ActiveRecord/Callbacks.html), only `after_commit` guarantees, that the record in question has been in fact saved to the database, and thus it's fair to index it into Elasticsearch (a database transaction might roll back an operation). Hence, the current implementation in the `Callbacks` module, and the accompanying documentation, prefer consistency coming from the database.

As you correctly point out, though, we might end up with _another_ inconsistency, where the record is not correctly indexed into Elasticsearch, due to conditions you mention.

So the decision here is to what is the "lesser danger". I would say that in many use cases (Elasticsearch index is secondary to the database), it's the current situation: hopefully someone is analyzing or reading the logs, and seeing the errors coming from failed indexing operations... But of course, it's a decision to make.

But the more important point to me is that the "automatic" `Callbacks` module is really only a _starting point_, and the documentation tries to emphasize this point a lot. For almost **any** serious application, you need to implement a custom indexing strategy, most definitely with some mechanism to perform the operation in background -- as the README suggests and provides examples for. In this case, there's probably some kind of monitoring of failed requests in Sidekiq (Resque, RabbitMQ, ...) and thus some visibility.

Does this all make sense? What do you think?

**Comment by cgagon** [comment]
I think we should document the fact that the Callbacks mixin can lead to divergence and consistency issues if there isn't a general solution here.

**Comment by karmi** [comment]
I'm all for it -- provided it's not as long as my answer above... If you can come up with wording, can you submit a PR, which I might edit, and close this issue?
