### ISSUE TITLE
Elasticsearch::Model::Callbacks not working for updates 

### ISSUE THREAD

**Issue by akhilaraop** [elastic/elasticsearch-rails#499]
Hi I have a file called as blog.rb 

where I have added these two lines: 

include Elasticsearch::Model
include Elasticsearch::Model::Callbacks

Then I have the dsl in my code: 

```
def self.search(query_term)
__elasticsearch__.search(
 {
"query" =>{
    "filtered" => {
        "query" => {
            "multi_match" => {
                "query" => query_term,
                "fields" => ["name", "blog_entry"]
            }
        },
        "filter" => {
            "term" => {"public_flag"=> true}
        }
    }
}
}).records
end
```

I have set up elasticsearch service in my local environment, am able to access the same via postman. Search works if there is a brand new entry, even deletion works fine. But if I update the blog_entry, the search doesnt work on updated blog entry. I wait for few minutes, still the search doesnt bring back the updated entry. Should I be adding this statement in my code?

```
 Blog.__elasticsearch__.refresh_index! 
```

**Comment by niuage** [comment]
Have you tried setting up the callback yourself like shown in the readme?

**Comment by xpepermint** [comment]
+1

**Comment by Awea** [comment]
I get the same issue and I've tryed with custom callback.

**Comment by niuage** [comment]
The elasticsearch-model gem basically adds a `before_save` callback setting an instance variable with the attributes that changed (`@__changed_attributes`). Then in the update_document method, it's using this variable to know what to update.

You should open the gem manually (`bundle open elasticsearch-model`) and make sure that the right attributes are present when updating your model (write a test for it, it makes it easier).

Personally, the issue I was having (and still have, but I'll probably be able to fix it easily now that I understood it), is that it doesn't work well with this: `store :extra, accessors: [:notes, :drops, :mods], coder: JSON`, the `store` feature of rails. The reason is that `model.changes` will return something like `{ extra: { notes: [], etc } }`, and that doesnt correspond with what `as_indexed_json` returns :(
