### ISSUE TITLE
Cannot update some field in elasticsearch use as_indexed_json help me please?

### ISSUE THREAD

**Issue by kenshero** [elastic/elasticsearch-rails#545]
my code "as_indexed_json"

```
  def as_indexed_json(options={})

    @article = {
      article_name: self.article_name,
      author_name: @author_name
    }

    @result = @article
    # binding.pry
    @result.as_json(
      only: [:article_name,:author_name]
    )

  end
```

my problem is ":article_name" can update in elasticsearch but ":author_name" cannot update 
sample my "@result " is  =  {:article_name=>"nametest", :author_name=>["ken1", "ken2"]}

But can insert @result to elasticsearch is correct but cannot update only author_name type array 

note : author_name is "select_option" in html  
I test author_name with " text_box" so can update But  i want to use "select_option"

How i can fix ? 

Thank you.

**Comment by karmi** [comment]
Hi, I'm sorry but I don't understand clearly what is your problem here -- the code you're posting doesn't give much hint as well.

If you wanna serialize your `Article` instance, why not just do something like?

```ruby
self.as_json( only: [:article_name, :author_name] )
```

You can pass multiple values to any field in Elasticsearch.

If `as_json` semantics trip you up, why not just construct the Hash manually?

```ruby
def as_indexed_json(options={})
  { article_name: self.article_name, author_name: self.author_name } 
end
```

**Comment by kenshero** [comment]
now , i can updated . i just use two callback function is "after_initialize" and "after_update" for one function so can updated . I am still confuse . Haha
