### ISSUE TITLE
Error when trying to import too much data in one batch

### ISSUE THREAD

**Issue by djudd** [elastic/elasticsearch-rails#575]
See https://github.com/elastic/elasticsearch-ruby/issues/314

@karmi asked me to open an issue here in the belief that it may be more logical to implement a workaround in this gem (I'm not sure I agree)

**Comment by karmi** [comment]
So, the original report in elastic/elasticsearch-ruby#314 is that when a batch which overpasses the `http.max_content_length` limit is sent to the `_bulk` API, an unusable exception is raised.

I think we should fix the issue here in the `Elasticsearch::Model::Importing#import` method, not in the Ruby client itself -- see my explanation here: https://github.com/elastic/elasticsearch-ruby/issues/314#issuecomment-224985054
