### ISSUE TITLE
Gemfile.lock

### ISSUE THREAD

**Issue by nysthee** [elastic/elasticsearch-rails#593]
Wouldn't I be a better idea to add a Gemfile.lock in the repo as ci-builds are failing all over it because of incompliant gem versions.

**Comment by karmi** [comment]
Hi, yes, the failures at Travis bother me, but I don't want to add the Gemfile.lock file to Git, since I'm afraid we won't catch incompatibilities with new gems soon, and also worried about the need to include the changes in Git history... I'll have a look at Travis and try to debug what's going on in there when I'll have some time.
