### ISSUE TITLE
Override __batch_to_bulk method

### ISSUE THREAD

**Issue by havran** [elastic/elasticsearch-rails#624]
Hi. 

I have ActiveRecord model with data stored in one JSON. I want break this data to relation

one model record -> multiple Elasticsearch records

For example JSON data looks like this:

```
{
  id: 1,
  items: [
    { id: 11, value: 0 },
    { id: 12, value: 1 },
    { id: 13, value: 1 },
  ]
}
```

I want store this data in elasticsearch as documents:

```
{ index: { _id: '1-11', data: { submit_id: 12345, form_id: 1, item_id: 11, value: 0 } } }
{ index: { _id: '1-12', data: { submit_id: 12345, form_id: 1, item_id: 12, value: 1 } } }
{ index: { _id: '1-13', data: { submit_id: 12345, form_id: 1, item_id: 13, value: 1 } } }
```

I can simple override callbacks for create, update and destroy but i want override Model.import method too. I realize i need override __batch_to_bulk method.

It is this best way how to achieve this? Thanks.

**Comment by karmi** [comment]
Hi, it's a good question! I think that when the requirements of an application diverge significantly from the assumptions of the library, it's better to implement the exact requirements in custom code, instead of reaching into the library code (whether by overriding, monkey patching, or other mechanism).

In this case, you would have a custom callback for the create/update/destroy/etc workflows attached to your ActiveRecord models, which would split the JSON into separate documents and manage them.

That would also apply to the importing logic -- although the importing code is quite complex, to be able to support all the different customizations people want to do, it's basically a ["find in batches and store each batch via bulk to ES"](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/importing.rb#L122) routine at its core. It shouldn't be more than a dozen lines of Ruby in your case, and you're free to do _anything_ special there, without reaching deep into the library.

At least that's my view of things in these cases -- what do you think?

**Comment by havran** [comment]
Thanks for answer. I wanted use Elasticsearch::Model for create index part and so on. 
I try use custom logic then. Thanks again.

**Comment by karmi** [comment]
Attention: I've never said you shouldn't use the conveniences in Elasticsearch::Model for setting up the index mapping, creating the indices, and so on. Just that handling the _indexing_ logic (whether for individual documents or for importing) makes more sense in custom Ruby code, using the building blocks provided by the gems, makes more sense.

**Comment by havran** [comment]
Ok, then i need only deal with import method. Replacing standard index/update/delete documents methods in callbacks is clear. Thanks again.

**Comment by karmi** [comment]
Cool, just update the issue or open a new one if you need assistance. Can you please close this issue if the problem at hand has been resolved?

**Comment by havran** [comment]
Thanks.

**Comment by derosm2** [comment]
I have a slightly different scenario where I want to override __batch_to_bulk to run some SQL to generate the JSON a bit more efficiently than calling as_indexed_json on each record.

Initially I was heading down the path of just writing a custom import method, but felt there were many conveniences I'd miss out on by using the provided import method (such as recreating the index and the associated rake task).

Should I monkey-patch the __batch_to_bulk method or is there an alternative I'm missing?

Thanks!

**Comment by derosm2** [comment]
Another thought would be providing an option for batch_to_bulk, similar to the transform. I don't think that would work well with the rake task though.
