### ISSUE TITLE
Instrumentation ES query log output as pure JSON

### ISSUE THREAD

**Issue by havran** [elastic/elasticsearch-rails#641]
Sometimes is useful copy ES query from log and use them in Kibana or curl. For now is output formated as Javascript object:
```
{index: "form-submits-development", type: "form_submit", body: {size: 135, query: {bool: {must: [{term: {form_id: 2}}, {range: {created_at: {gte: "2016-09-09||/d", lte: "2016-11-16||/d", format: "yyyy-MM-dd"}}}]}}, _source: ["id", "created_at", "items.id", "items.values"], from: 0, sort: [{created_at: {order: "desc"}}, {id: {order: "desc"}}]}}
```
JSON:
```
{"index":"form-submits-development","type":"form_submit","body":{"size":135,"query":{"bool":{"must":[{"term":{"form_id":2}},{"range":{"created_at":{"gte":"2016-09-09||/d","lte":"2016-11-16||/d","format":"yyyy-MM-dd"}}}]}},"_source":["id","created_at","items.id","items.values"],"from":0,"sort":[{"created_at":{"order":"desc"}},{"id":{"order":"desc"}}]}}
```
which prevent use simple copy/paste approach for this.

Output is created by this line of code, from inspect output https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/elasticsearch/rails/instrumentation/log_subscriber.rb#L31

Maybe use configurable to_json option would be useful?

**Comment by karmi** [comment]
Hi, I understand the reasoning. I guess the motivation for the "JS-like" formatting is to save space.

I'm not opposed to a configuration option, but I am wondering how to properly expose that. It would be great if we could hook into the `config.*` namespace of Rails' environment configuration, similar to [lograge](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/elasticsearch/rails/lograge.rb#L36), and set it there. Otherwise, it would have to be a `LogSubscriber.configure` class method directly in the code, and would have to be called somewhere in the application code, probably an initalizer.

Is it something you'd be interested in exploring?
