### ISSUE TITLE
Is this gem abandoned?

### ISSUE THREAD

**Issue by dgmora** [elastic/elasticsearch-rails#659]
First of all, I don't want to sound harsh; the amount of work put here and what it provides is amazing! 

There's a big number of unaddressed issues, PRs that are not merged nor commented and (apparently) tests are failing since long. So I would just like to know better if this gem has a future or not.

**Comment by karmi** [comment]
Hi @dgmora, you're not sounding harsh and your concern is justified. It is true that I have been neglecting this particular repository for some time. I had to focus on other responsibilities, and wasn't able to find time for this one.

In particular, I have spent quite some time on the sibling repository, https://github.com/elastic/elasticsearch-ruby, which provides a low-level Ruby client and a couple of widely used extensions, and which also serves as a basis for the Rails integrations in this repository. I have been able to clear up most of the pull requests and issues there, notably when it comes to compatibility with various Elasticsearch versions, and plan to switch focus to the Rails integrations in this repository in the coming weeks and months (notably, again, revisiting compatibility with Elasticsearch versions).

So no, this gem is definitely not abandoned. It is just that I have kept focus on the other set of libraries.

P.S.

What's not very evident from the outside perspective, perhaps, is that even small pull requests come with some overhead, sometimes a considerable overhead: I have to understand the intention there, find other related issues or patches, review the changes and sometimes ask for changes, verify (and sometimes add) the tests locally, clean up and annotate the commit messages, merge into appropriate branches. I guess I could make my life easier if I would just click the "Merge" button, but I don't want to risk the chance that the codebase falls totally apart...

**Comment by dgmora** [comment]
Thanks for the clarification! For the elasticsearch versioning and PRs overhead, I guess it'd be helpful if you could test against multiple versions. I used docker (install docker, `docker run elasticsearch`; or per version `docker run elasticsearch:5.1.2`) to have `elasticsearch` running easily for the tests.

**Comment by karmi** [comment]
Thanks for the understanding!

Testing against multiple version of Elasticsearch is not really a problem -- notice I haven't even included it in my list of problems :)

I use the [`Test::Cluster`](https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-extensions/lib/elasticsearch/extensions/test/cluster.rb) extension for that, which is also used at Travis with the `SERVER=start` environment variable for the `elasticsearch-ruby` group of gems. The only thing needed to be done is to download & extract the appropriate versions.

I'll close this issue if it's OK -- since I've managed to clear up most of the pending issues in the `elasticsearch-ruby` repository, I'll switch focus to this repository next.
