### ISSUE TITLE
Sometime `@__changed_attributes` have {} value.

### ISSUE THREAD

**Issue by dim0627** [elastic/elasticsearch-rails#743]
```
elasticsearch-rails (5.0.1)
rails (= 5.1.3)
```

ActiveRecord's `update_attributes` does return `{}` from `instance.changes` when don't have changed record.

`update_attribute` runs below.

``` ruby
pry(main)> job = Job.first
pry(main)> puts job.title
Updated1
pry(main)> job.update_attribute(:title, 'Updated1')
pry(main)> puts job.__elasticsearch__.instance_variable_get(:@__changed_attributes)

=> nil
```

`update_attributes` runs below.

``` ruby
pry(main)> job = Job.first
pry(main)> puts job.title
Updated1
pry(main)> job.update_attributes(title: 'Updated1')
pry(main)> puts job.__elasticsearch__.instance_variable_get(:@__changed_attributes)
{} # what's up!
=> nil
```

This behavior affects `def update_document(options={})` method.

https://github.com/elastic/elasticsearch-rails/blob/5.x/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L394

`if changed_attributes = self.instance_variable_get(:@__changed_attributes)` evaluated `true` but `changed_attributes` is `{}`.
Finally, send request to elasticsearch empty update.

I guess `@__changed_attributes` should not have `{}`, It is correct specification this gem?

**Comment by nilbus** [comment]
BTW, the line number to the referenced line has changed in the 5.x branch. Here's a permalink: https://github.com/elastic/elasticsearch-rails/blob/d8859aed2aa75c93840b763d70e8fce8ce7761ff/elasticsearch-model/lib/elasticsearch/model/indexing.rb#L394

---

The behavior you see happens because `update_attribute` [does nothing][] when there are no changes to save, thus bypassing the `before_save` filter that sets `@__changed_attributes`. However `update_attributes` (`update`) [does not check][] whether there were updates before saving.

[does nothing]: https://github.com/rails/rails/blob/695ec1fef0b7fdb3125a3e2e4364a7f449265c1b/activerecord/lib/active_record/persistence.rb#L405
[does not check]: https://github.com/rails/rails/blob/695ec1fef0b7fdb3125a3e2e4364a7f449265c1b/activerecord/lib/active_record/persistence.rb#L415-L424

I can see how requesting an empty update to elasticsearch could generate a lot of needless overhead in cases where your application performs many `update_attributes` operations, passing attributes that may or may not be empty.
