### ISSUE TITLE
Deprecation Warning - Rails 5.1 - nothing

### ISSUE THREAD

**Issue by wisetara** [elastic/elasticsearch-rails#760]
I would happily submit a PR for this if I could track it down, but I haven't been able to do so.

This [line](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/elasticsearch/rails/instrumentation/controller_runtime.rb#L20) is causing a deprecation warning: `DEPRECATION WARNING: `:nothing` option is deprecated and will be removed in Rails 5.1. Use `head` method to respond with empty response body. (called from cleanup_view_runtime at [link above](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-rails/lib/elasticsearch/rails/instrumentation/controller_runtime.rb#L20).

I know `super` is a Float at that point, and when I tracked it back into rails, which caused me to look in their `instrumentation.rb#render` [method](https://github.com/rails/rails/blob/a52ff1b0848e8bb2310738ec7b762b82edbbfcb2/actionpack/lib/action_controller/metal/instrumentation.rb#L43), but then my ability to track just fails. I'm happy to put in a PR somewhere if I can just find the source... but I'm not even sure I'm looking in the right place.

**Comment by nilbus** [comment]
Here's a link to the Rails source where you can find the deprecation message you reported: [rails/rails@5-0-stable:…/rendering.rb#L102](https://github.com/rails/rails/blob/a02a8d72de5a04b5e0504067083ec1d043b62c5f/actionpack/lib/action_controller/metal/rendering.rb#L86-L102)

Looking at the lines around it, you'll see that this is the code handling options to `render` calls in controller actions, as in:

```ruby
def update
  # perform update
  render :nothing # This is deprecated in Rails 5
end
```

I think you're seeing elasticsearch-rails's `cleanup_view_runtime` method in your stack trace because elasticsearch-rails [adds instrumentation][includes] around the Rails version of this method, which is called by [`render`][render].

[includes]: https://github.com/elastic/elasticsearch-rails/blob/15761247f3e99654bda946a178e50b5365414b59/elasticsearch-rails/lib/elasticsearch/rails/instrumentation/railtie.rb#L24
[render]: https://github.com/rails/rails/blob/a52ff1b0848e8bb2310738ec7b762b82edbbfcb2/actionpack/lib/action_controller/metal/instrumentation.rb#L43-L45

To resolve this error, check your controllers for use of `render :nothing`. The good news is that you since this isn't originating from elasticsearch-rails, you can probably resolve the warning with only changes in your app.

**Comment by estolfo** [comment]
Hi @wisetara 
Were you able to resolve this? Can we close this issue?
Thanks

**Comment by wisetara** [comment]
I wasn't able to resolve it, but it seems like it may not be related to elasticsearch-rails, so go ahead and close. Thank you.
