### ISSUE TITLE
#records Elasticsearch::Model::NotImplemented on ActiveRecord 4.2.0 ?

### ISSUE THREAD

**Issue by pjfitzgibbons** [elastic/elasticsearch-rails#773]
```
class Widget < ActiveRecord::Base
  include Elasticsearch::Model
end
```

```
irb(main):010:0> Widget.search('fox').results.records
Elasticsearch::Model::NotImplemented: Implement this method in #<Elasticsearch::Model::Proxy::ClassMethodsProxy:0x0000557d573d81a8>
        from /myapp/vendor/bundle/gems/elasticsearch-model-5.0.2/lib/elasticsearch/model/response/base.rb:27:in `records'
        from (irb):10
        from /myapp/vendor/bundle/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
        from /myapp/vendor/bundle/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
        from /myapp/vendor/bundle/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
        from /myapp/vendor/bundle/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
        from /myapp/vendor/bundle/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
        from bin/rails:4:in `require'
        from bin/rails:4:in `<main>'
```

I'm not allowed to give much more context than that.

Any general ideas on why this would be happening?

"Yesterday it worked fine".

Maybe, is there an Elasticsearch::Model method to erase __ALL__ of the indices in the ES server?

Thanks and Kindest Regards,
Peter Fitzgibbons

**Comment by karmi** [comment]
That's really a weird error. Your `include` directive is all right. The "not implemented" exception is surprising, because the library does a bit of introspection, and picks up an "adapter" for the specific model class, eg. [ActiveRecord](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/lib/elasticsearch/model/adapters/active_record.rb).

Can you run [this simple example](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_article.rb) with the versions you have in your application, and see it you'd get the same error?

**Comment by estolfo** [comment]
Hi @pjfitzgibbons 
Have you been able to resolve this? 
If not, would you mind running the simple example linked in the comment above and see if you get the same error?
Thanks

**Comment by estolfo** [comment]
Hi @pjfitzgibbons I'm going to close this issue. Please open a new one if you have further questions.
