### ISSUE TITLE
Cannot filter on property fields with ES 6.x

### ISSUE THREAD

**Issue by tylercrocker** [elastic/elasticsearch-rails#789]
We've had an ES system set up in the past but with ES 2.4 and when we did that we were able to define fields with custom analyzers on object properties like so:

```ruby
mappings do
  indexes :my_object do
    indexes :property_a, { type: "string", index: "not_analyzed" }

    indexes :property_b, type: "multi_field", fields: {
      default: { type: "string", index_options: "offsets" },
      exact: { type: "string", index: "not_analyzed" },
      exact_lowercase: { type: "string", analyzer: "keyword_lowercase" }
    }
...
```

And we've set up that custom analyzer here:

```ruby
settings analysis: {
  filter: {},
  tokenizer: {},
  analyzer: {
    keyword_lowercase: {
      tokenizer: "keyword",
      filter: ["lowercase"]
    }
  }
}
```

In the past we were then able to run queries like so (my code from Kibana):

```
GET SOME_INDEX/_search
{
  "query": {
    "bool": {
      "filter": [
        {
          "term": {
            "property_b.exact_lowercase": "multi word value"
          }
        }
      ]
    }
  }
}
```

Which worked fine. But we're trying to upgrade our system to use all the latest and greatest, and MOST things seem to work just fine, except for filtering on that "exact_lowercase" bit.

The new indexing code we're using looks like this (with the same analyzer definition):

```ruby
mappings do
  indexes :my_object do
    indexes :property_a, type: "text"

    indexes :property_b, type: "text" do
      indexes :exact, type: "keyword"
      indexes :exact_lowercase, type: "keyword", analyzer: "keyword_lowercase"
    end
...
```

We can search on just "property_b" but then it's tokenizing individual words, and we need to be able to do an exact full-match on the field.

We could index the field as type keyword to begin with I think, but we also would like to be able to search it via non-exact match search.

EDIT: As a followup, I tried just indexing "property_b" as a keyword and that also does not appear to work...

Anyone have any insight? I feel like I must be doing something stupid somewhere.

**Comment by karmi** [comment]
Hi @tylercrocker, thank you for such a detailed explanation. Nothing jumps on me from the code you have attached, so either we're both overlooking something, or the problem is elsewhere. I'm afraid I can't dedicate time to replicate in Ruby code at the moment, but I have couple of suggestions:

1. First, I'd try looking if the analyzer is doing what you expect it to do, by using the `_analyze` API, see [Ruby client documentation](http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Indices/Actions#analyze-instance_method).

2. If that all fits, I'd use the `trace: true` option for the client, to dump the requests in `curl` format, and post an isolated example to the [Elastic forum](https://discuss.elastic.co). There doesn't seem to be a peculiarity with the Ruby aspect, at the moment, so somebody can have a better idea.

**Comment by karmi** [comment]
>  I'm still looking into how to tell it to not index EVERYTHING I'm storing.

Unless your use case is really specific (eg. limit disk space for big documents, ...), I'm not sure if it's worth it to fine-tune the properties like this. I would just index all the properties, since then you can search/aggregate them, etc.

>  I've found a bunch of information about telling the field to "index: false", (...)

Yeah, this configuration went through many changes over the versions, right now, you should use the [`enabled`](https://www.elastic.co/guide/en/elasticsearch/reference/current/enabled.html) configuration in the index mapping.

> I DID notice that ALL of the fields I'm describing in my as_indexed_json method are being indexed as both the regular field (property_x) as well as a .keyword (property_x.keyword) version of the field.

Yes, this is now done automatically, to allow people unaware of how mapping influences search/aggregations (eg. you can't run a `terms` aggregation or sort on field like `full_name`, when it's analyzed). Some background in this [blog post](https://www.elastic.co/blog/strings-are-dead-long-live-strings).

**Comment by tylercrocker** [comment]
@karmi Oh, I forgot to talk about the enabled bit... I actually tried that, but I get an error in ES saying:

```
Mapping definition for [some_property] has unsupported parameters:  [enabled : false]
```

This is using ES 6.2.3 and the gems as:

```
gem 'elasticsearch', '~> 6'
gem 'elasticsearch-rails', '~> 5'
gem 'elasticsearch-model', '~> 5'
```

"index: false" passes through just fine, but doesn't affect anything.

If what you said about just letting things index by default is fine I guess I won't worry about that for now, but it'd be nice to be able to fine-tune things a little bit eventually :)

**Comment by tylercrocker** [comment]
SOLVED!!!

I finally figured out my problem was with our bulk indexing method. With the old system it worked fine to set up the index for the model and call `.create_index! force: true` once and then you were golden, all subsequently created indexes were created based on that. But with the new system I have to forcefully create EVERY index (we create daily indexes based on the primary one we have... probably a weird setup)

So in our custom bulk insert method I had to add the following before actually inserting into the index to make sure it was created properly:

```ruby
unless MyModel.__elasticsearch__.client.indices.exists? index: index
  MyModel.__elasticsearch__.create_index! index: index, force: true
end
```

This resolved ALL of my issues and everything works exactly as I had expected it to!

**Comment by karmi** [comment]
Ah, nice, thanks for report, @tylercrocker!

(BTW, ["Index Templates"](https://www.elastic.co/guide/en/elasticsearch/reference/6.x/indices-templates.html) help a lot with time-based indices, might be useful to look at it.)

**Comment by tylercrocker** [comment]
@karmi yeah a coworker literally just told me about that... haha. I'm going to be looking into that once I have time for sure since it's obviously a better way to deal with that.

Thanks for all your help btw!

**Comment by karmi** [comment]
> it's obviously a better way to deal with that

Not always :) Sometimes the Ruby code is more transparent to understand for everybody on the team, as opposed to "magical" indices :)

You're welcome!
