### ISSUE TITLE
Datetime is not getting saved.

### ISSUE THREAD

**Issue by magedmakled** [elastic/elasticsearch-rails#817]
[This issue](https://stackoverflow.com/questions/51468588/elasticsearch-date-invalid-format-too-short) If I created a document from model `save` I get 

`Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"failed to parse [starts_at]"}],"type":"mapper_parsing_exception","reason":"failed to parse [starts_at]","caused_by":{"type":"illegal_argument_exception","reason":"Invalid format: \"2018-07-29\" is too short"}},"status":400}` 

But when I used curl or something like postman, it works fine and saves it correctly. 

Another issue even for the successful postman post, the Model find return the field as date only, when I only as for the  `_source` , it would show the field as datetime 

**Updates**

My model is `Elasticsearch::Persistence::Model`  
The starts_at field `attribute :starts_at, Date, mapping: { format: "yyyy-MM-dd'T'HH:mm:ssZ" }` and getting mapped correctly
```
"starts_at": {
               "type": "date",
               "format": "yyyy-MM-dd'T'HH:mm:ssZ"
             }
```

**Creating** 

```
starts = DateTime.parse("Sunday July 29th 8:00am cdt").iso8601
ends = DateTime.parse("Sunday July 29th 10:00am cdt").iso8601

hash = {
        location_name: "some location",
        starts_at: starts,
        ends_at: ends,  #Both starts_at and ends_at have the same settings in the model
        required: false,
        street_address: "some address",
        city: "St. Paul",
        state:"MN",
        zip: "12345"
      }

Event.create(hash)
```

**Comment by estolfo** [comment]
Hi @magedmakled, in order to help answer your question, can you please share the following:
Whether you are using `Elasticsearch::Persistence::Model`?
How you are creating the mapping for the `starts_at` field in the model (the Ruby code).
The Ruby code where you are trying to create the document in Elasticsearch.
The result of calling `#to_json` on the model instance that you are trying to index into Elasticsearch.
Thanks!

**Comment by magedmakled** [comment]
@estolfo updated the question, Thanks

**Comment by estolfo** [comment]
Hi @magedmakled, The reason you are getting the error is because the String returned from calling `iso8601` on the Datetime doesn't exactly match what you've defined as the date format for the `starts_at` field in the index mapping.
I would recommend instead doing something like this:
```ruby
date = DateTime.parse("Sunday July 29th 8:00am cdt")
starts = date.strftime("%Y...") # Set up the format here that matches the starts_at field mapping
```
Let me know if that works!

**Comment by estolfo** [comment]
@magedmakled Did you get a chance to try my suggestion in the previous comment? Let me know, thanks!

**Comment by estolfo** [comment]
I'm going to close this issue. Please open a new one if you have further questions.

**Comment by magedmakled** [comment]
Sorry for the late response. That didn't work, I will open a new ticket and write more detailed description
