### ISSUE TITLE
Result window is too large even with pagination

### ISSUE THREAD

**Issue by matteoredz** [elastic/elasticsearch-rails#841]
I'm trying to get page XXX (1288) with Kaminari for a ElasticSearch result object and it states:

`[500] {"error":{"root_cause":[{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [12880]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"questions","node":"WFpf1ie1TqCgZxWNHLZv4g","reason":{"type":"query_phase_execution_exception","reason":"Result window is too large, from + size must be less than or equal to: [10000] but was [12880]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting."}}]},"status":500}`

My search action contains following

`Elasticsearch::Model.search(body, klass).page(@page).per(10).results` 

where

`
body = {
      size: 10,
      query: { match: { _all: { query: @es_key, cutoff_frequency: 0.001, zero_terms_query: 'all' } } },
      sort: [{ _score: :desc }]
    }
`

and `klass` is my search Model.

I wouldn't increate max_window_search but I'd like to use something like offset (from, search_after) to offset results..

It looks like that none of them is available in gem DSL

**Comment by estolfo** [comment]
@matteoredz Thanks for your question. As the documentation says [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html) for the scroll API, it’s not intended for realtime user requests but rather more for data-processing. It’s quite resource-intensive so I would not recommend building user-facing functionality with it. This is why you’ll find that the pagination implementation via the search API is done without using the scroll parameter.

You are welcome to write your own search requests using the scroll API or write your own Pagination adapter. Would this be an option for you? Otherwise, we can explore allowing a scroll option for pagination though I'm not sure how useful this would be.

**Comment by estolfo** [comment]
@matteoredz Did you have a chance to read my comment above?

**Comment by estolfo** [comment]
@matteoredz 
ok, thanks for your response. I'm going to close this issue, if you don't mind.

**Comment by schezwansoftware** [comment]
I am still confused, How can i using paging to avoid this issue as i think using Scroll API here is not necessary
