### ISSUE TITLE
Questions about the create_index! method

### ISSUE THREAD

**Issue by shunta27** [elastic/elasticsearch-rails#919]
When you execute the instance method of the repository class that includes the "Elasticsearch :: Persistence :: Repository" module. create_index! (Index: 'test_index'), nil is returned. Which is this a bug or my bad use?

**Comment by oriahu** [comment]
I have a question that might follow on from this one.

Should we expect indexing ClassMethods to continue to work on a Repository class, as class methods? They seem to work just fine as instance methods because they are [`included` directly into the repository](https://github.com/elastic/elasticsearch-rails/blob/6.x/elasticsearch-persistence/lib/elasticsearch/persistence/repository.rb#L19).

### **Some Context**

Noticed this in the [DSL module](https://github.com/elastic/elasticsearch-rails/blob/6.x/elasticsearch-persistence/lib/elasticsearch/persistence/repository/dsl.rb#L10):

```
        def self.included(base)
          base.send(:extend, Elasticsearch::Model::Indexing::ClassMethods)
          base.send(:extend, ClassMethods)
        end
```

When calling `Repository.create_index!`, i get the following error:
```
*** NotImplementedError Exception: The 'create_index!' method is not implemented on the Repository class.
```

When i checked the Repository ancestors noticed:
```
[ ..., Singleton, Elasticsearch::Persistence::Repository::DSL, Elasticsearch::Persistence::Repository, Elasticsearch::Model::Indexing::ClassMethods, ...]
```

It seems like the DSL module, when included, will override the Indexing ClassMethods set on the Respository class with it's own stubbed out and unimplemented class methods via: `base.send(:extend, ClassMethods)`

I think the fix could be to switch those two lines around in the `self.included(base)` method.

A workaround might be to just extend with the indexing class methods explicitly, ie where i include DSL, but actually haven't gotten this working yet 😅

```
    include Elasticsearch::Persistence::Repository::DSL
    extend Elasticsearch::Model::Indexing::ClassMethods
```

**Comment by shunta27** [comment]
Thank you.
Using the repository class, I was able to solve what I wanted to do.
