### ISSUE TITLE
Need help on the elastic version

### ISSUE THREAD

**Issue by nandueverurs** [elastic/elasticsearch-rails#949]
Hi,
Can some one please help me on this version. I am planning to update the gem .

Does the 7.1 version supports elastic 7.8 version with ruby 2.3 and rails 4.0.2?

**Comment by picandocodigo** [comment]
Hi @nandueverurs, 
7.1 should work fine with Elastic Stack 7.8. However Ruby 2.3 has reached it's end of life and is not receiving updates anymore. The gem might still work with this version of Ruby, but we can't guarantee it does since we don't test newer releases with EOL'd versions of Ruby. If you find any specific problems on the update, please open a new issue and I'll try to help out.

**Comment by nandueverurs** [comment]
Hi @picandocodigo 
Thanks Very much for your help. Will post here if we run into any problems. Closing this now.
